export const cards = [
    {
      id: 1,
      title: "WallScapes",
      // desc: "Add talent to AI",
      img: "./img/1.jpg",
    },
    {
      id: 2,
      title: "Poster",
      // desc: "Build your brand",
      img: "./img/23.jpg",
    },
    {
      id: 3,
      title: "Digital BillBoards",
      // desc: "Customize your site",
      img: "./img/bill2.jpg",
    },
    {
      id: 4,
      title: "Banner",
      // desc: "Engage your audience",
      img: "./img/4.jpg",
    },
    {
      id: 5,
      title: "Street furniture",
      // desc: "Professional Product Images",
      img: "./img/2.jpg",
    },
    {
      id: 6,
      title: "BillBoards",
      desc: "Reach more customers",
      img: "./img/6.png",
    },
    {
      id: 7,
      title: "Illustration",
      desc: "Color you dreams",
      img: "./img/7.jpg",
    },
    {
      id: 8,
      title: "Advertisement maker",
      desc: "Creative Ad Campaign",
      img: "./img/8.png",
    },
    {
      id: 9,
      title: "News Letter",
      desc: "Informative Email Digest",
      img: "./img/9.png",
    },
    {
      id: 10,
      title: "Poster",
      desc: "Impactful Visual Communication",
      img: "./img/10.png",
    },
  ];
  
  export const projects = [
    {
      id: 1,
      img: "./img/lo1.jpg",
      pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Web and Mobile Design",
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "./img/lo2.jpg",
      pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Logo Design",
      username: "Morton Green",
    },
    {
      id: 3,
      img: "./img/lo3.jpg",
      pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Animated GIFs",
      username: "Emmett Potter",
    },
    {
      id: 4,
      img: "./img/lo4.jpg",
      pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Packaging Design",
      username: "Freddie Johnston",
    },
    {
      id: 5,
      img: "./img/lo5.jpg",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Social Media Design",
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "./img/lo6.jpg",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Illustration",
      username: "Dalton Hudson",
    },
    {
      id: 7,
      img: "./img/lo7.jpg",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Book Design",
      username: "Hannah Dougherty",
    },
    {
      id: 8,
      img: "./img/lo8.jpeg",
      pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Digital Marketing",
      username: "Ward Brewer",
    },
  ];
  
  // export const gigs = [
  //   {
  //     id: 1,
  //     img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create ai art character from your images and prompts",
  //     price: 82678,
  //     star: 5,
  //     username: "Anna Bell",
  //     title: "Wallscapes",
  //   },
  //   {
  //     id: 2,
  //     img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create ultra high quality character art with ai",
  //     price: 7999,
  //     star: 5,
  //     username: "Lannie Coleman",
  //     title: "Poster",
  //   },
  //   {
  //     id: 3,
  //     img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will creating unique ai generated artworks mid journey ai artist",
  //     price: 1199,
  //     star: 5,
  //     username: "Carol Steve",
  //     title: "Digital Billboards",
  //   },
  //   {
  //     id: 4,
  //     img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create custom ai generated artwork using your photos",
  //     price: 9999,
  //     star: 4,
  //     username: "Don Weber",
  //     title: "Billboards",
  //   },
  //   {
  //     id: 5,
  //     img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will recreate your dreams in high quality pictures",
  //     price: 5999,
  //     star: 5,
  //     username: "Audrey Richards",
  //     title: "Street Furniture",
  //   },
  //   {
  //     id: 6,
  //     img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create ai digital art illustration hyper realistic painting",
  //     price: 7999,
  //     star: 4,
  //     username: "Walton Shepard ",
  //     title: "Wallscapes",
  //   },
  //   {
  //     id: 7,
  //     img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will generate images with your prompts using ai dalle",
  //     price: 8999,
  //     star: 5,
  //     username: "Waverly Schaefer",
  //     title: "Poster",
  //   },
  //   {
  //     id: 8,
  //     img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create custom art using midjourney generator",
  //     price: 1100,
  //     star: 4,
  //     username: "Wilton Hunt",
  //     title: "Digital Billboards",
  //   },
  // ];
  export const gigsdetails = [
    {
      id: 1,
      img: "/img/ws1.avif",
      pp: ["/img/ws1.avif",
          "/img/ws5.jpg",
          "/img/ws3.jpeg"
      ],
      desc: "Promote Your Brand on Prime Billboard Locations",
      price: 82678,
      star: 5,
      username: "Anna Bell",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc: "Transform Urban Spaces into Vibrant Brand Showcases.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 20 X 10 ft.",
        "Location: Nikol, Ahmedabad",
        "Target Audience: Youth, Fashion Enthusiasts",
        "Additional Design Elements:  Custom Branding,  Animations"
      ],
    },
    {
      id: 2,
      img: "/img/ps1.jpg",
      pp: ["/img/ps1.jpg",
          "/img/ps3.jpg",
          "/img/ps2.jpg"
      ],
      desc: "See. Believe. Act",
      price: 7999,
      star: 5,
      username: "Lannie Coleman",
      title: "Poster",
      shortTitle: "Posters",
      shortDesc: "Eye-Catching Posters for Maximum Street Impact.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 10 X 15 ft.",
        "Location: Maninagar, Ahmedabad",
        "Target Audience:  Families,  Foodies",
        "Additional Design Elements:  Special Effects"
      ],
    },
    {
      id: 3,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Your Message. Their Attention. Digital Billboards Make it Happen.",
      price: 1199,
      star: 5,
      username: "Carol Steve",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Engaging Digital Campaigns for Modern Audiences.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 15 X 25 ft.",
        "Location: Ellisbridge, Ahmedabad",
        "Target Audience:  Students, Young Professionals",
        "Additional Design Elements:  Interactive Features,  Animation",
      ],
    },
    {
      id: 7,
      img: "/img/ps2.jpg",
      pp: ["/img/ps2.jpg",
          "/img/ps3.jpg",
          "/img/ps1.jpg"
      ],
      desc: "Turn Heads. Stop Traffic",
      price: 8999,
      star: 5,
      username: "Waverly Schaefer",
      title: "Poster",
      shortTitle: "Posters",
      shortDesc: "Fun and Colorful Designs for Any Setting.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 10 X 15 ft.",
        "Location:  Satellite, Ahmedabad",
        "Target Audience:  Families,  Families with Children",
        "Additional Design Elements:  Bright Colors,  Fun Illustrations"
      ],
    },
    {
      id: 8,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Go Big, Go Bold, Go Digital: Elevate Your Campaign to New Heights.",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Minimalist Designs with Maximum Impact.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Minimalist Design,  Brand-Specific Imagery"
      ],
    },

    {
      id: 10,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Digital Billboards: Where Your Message Takes Center Stage",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Bold Designs that Make a Statement.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 10 X 12 ft.",
        "Location:  C.G. Road, Ahmedabad",
        "Target Audience:  Shoppers,  Fashion Enthusiasts",
        "Additional Design Elements:  Animation,  Special Effects"
      ],
    },
    {
      id: 11,
      img: "/img/ws3.jpeg",
      pp: ["/img/ws3.jpeg",
          "/img/ws4.webp",
          "/img/ws5.jpg"
      ],
      desc: "Turn your wallscape into a brand icon. Stand out from the crowd",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc: "Dynamic Visuals for Every Corner of the City.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 20 X 15 ft.",
        "Location:  Drive-In Road, Ahmedabad",
        "Target Audience:  Families,  Young Adults",
        "Additional Design Elements:  Custom Typography,  Brand-Specific Imagery"
      ],
    },
    {
      id: 12,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Amplify Your Message: Digital Billboards for the Modern Era.",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Captivate Audiences with Unique Ads.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 18 X 12 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Bold Colors,  Call to Action"
      ],
    },
    {
      id: 13,
      img: "/img/ws4.webp",
      pp: ["/img/ws4.webp",
          "/img/ws1.avif",
          "/img/ws5jpg"
      ],
      desc: "Your Brand, Their Everyday View: Captivating Wallscapes",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc: "Wallscapes: Where Art Meets Advertising.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 20 X 15 ft.",
        "Location:  Ashram Road, Ahmedabad",
        "Target Audience:  Students,  Young Professionals",
        "Additional Design Elements:  Interactive Elements,  Lighting Effects"
      ],
    },

    {
      id: 15,
      img: "/img/ws5.jpg",
      pp: ["/img/ws5.jpg",
          "/img/ws3.jpeg",
          "/img/ws4.webp"
      ],
      desc: "Make a Statement, Not Just an Ad: Wallscape Your Brand Story.",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc: "Urban Spaces Transformed with Innovative Art.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  Navrangpura, Ahmedabad",
        "Target Audience:  Families,  Shoppers",
        "Additional Design Elements:  Creative Typography,  Minimalist Style"
      ],
    },
    {
      id: 16,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Make a Mark. Make a Difference. Banner It Up.",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Banner",
      shortTitle: "Banner",
      shortDesc: "Minimalist Designs with Maximum Impact.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Minimalist Design,  Brand-Specific Imagery"
      ],
    },
    {
      id: 17,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Beyond the Ordinary. Banner Your Extraordinary.",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Banner",
      shortTitle: "Banner",
      shortDesc: "Minimalist Designs with Maximum Impact.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Minimalist Design,  Brand-Specific Imagery"
      ],
    },
    {
      id: 18,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Turn Heads. Turn the Tide. Banner Your Brand.",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Banner",
      shortTitle: "Banner",
      shortDesc: "Minimalist Designs with Maximum Impact.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Minimalist Design,  Brand-Specific Imagery"
      ],
    },
    {
      id: 5,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Turning Ordinary Moments into Extraordinary Ones.",
      price: 5999,
      star: 5,
      username: "Audrey Richards",
      title: "Street Furniture",
      shortTitle: "Street Furniture",
      shortDesc: "Blend Seamlessly into City Life with Stylish Ads.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 5 X 8 ft.",
        "Location: Ashram Road, Ahmedabad",
        "Target Audience:  Commuters,  Pedestrians",
        "Additional Design Elements:  Creative Typography,  Minimalist Style"
      ],
    },
    {
      id: 19,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: " Small Ads, Big Impact. Make Your Mark.",
      price: 5999,
      star: 5,
      username: "Audrey Richards",
      title: "Street Furniture",
      shortTitle: "Street Furniture",
      shortDesc: "Blend Seamlessly into City Life with Stylish Ads.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 5 X 8 ft.",
        "Location: Ashram Road, Ahmedabad",
        "Target Audience:  Commuters,  Pedestrians",
        "Additional Design Elements:  Creative Typography,  Minimalist Style"
      ],
    },
    {
      id: 20,
      img: "/img/12.png",
      pp: ["/img/12.png",
          "/img/13.png",
          "/img/14.png"
      ],
      desc: "Because You're Worth It. Every Day.",
      price: 5999,
      star: 5,
      username: "Audrey Richards",
      title: "Street Furniture",
      shortTitle: "Street Furniture",
      shortDesc: "Blend Seamlessly into City Life with Stylish Ads.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 5 X 8 ft.",
        "Location: Ashram Road, Ahmedabad",
        "Target Audience:  Commuters,  Pedestrians",
        "Additional Design Elements:  Creative Typography,  Minimalist Style"
      ],
    },
  ];
