export const cards = [
    {
      id: 1,
      title: "WallScapes",
      // desc: "Add talent to AI",
      img: "./img/1.jpg",
    },
    {
      id: 2,
      title: "Poster",
      // desc: "Build your brand",
      img: "./img/23.jpg",
    },
    {
      id: 3,
      title: "Digital BillBoards",
      // desc: "Customize your site",
      img: "./img/bill2.jpg",
    },
    {
      id: 4,
      title: "BillBoards",
      // desc: "Engage your audience",
      img: "./img/4.jpg",
    },
    {
      id: 5,
      title: "Street furniture",
      // desc: "Professional Product Images",
      img: "./img/2.jpg",
    },
    {
      id: 6,
      title: "BillBoards",
      desc: "Reach more customers",
      img: "./img/6.png",
    },
    {
      id: 7,
      title: "Illustration",
      desc: "Color you dreams",
      img: "./img/7.jpg",
    },
    {
      id: 8,
      title: "Advertisement maker",
      desc: "Creative Ad Campaign",
      img: "./img/8.png",
    },
    {
      id: 9,
      title: "News Letter",
      desc: "Informative Email Digest",
      img: "./img/9.png",
    },
    {
      id: 10,
      title: "Poster",
      desc: "Impactful Visual Communication",
      img: "./img/10.png",
    },
  ];
  
  export const projects = [
    {
      id: 1,
      img: "https://fiverr-res.cloudinary.com/q_auto,f_auto,w_550,dpr_1.0/v1/attachments/generic_asset/asset/aa2ff6a65708e858cd563bedbc1f9e48-1617004762616/spickex.jpeg",
      pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Web and Mobile Design",
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Logo Design",
      username: "Morton Green",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Animated GIFs",
      username: "Emmett Potter",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Packaging Design",
      username: "Freddie Johnston",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Social Media Design",
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Illustration",
      username: "Dalton Hudson",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Book Design",
      username: "Hannah Dougherty",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Digital Marketing",
      username: "Ward Brewer",
    },
  ];
  
  // export const gigs = [
  //   {
  //     id: 1,
  //     img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create ai art character from your images and prompts",
  //     price: 82678,
  //     star: 5,
  //     username: "Anna Bell",
  //     title: "Wallscapes",
  //   },
  //   {
  //     id: 2,
  //     img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create ultra high quality character art with ai",
  //     price: 7999,
  //     star: 5,
  //     username: "Lannie Coleman",
  //     title: "Poster",
  //   },
  //   {
  //     id: 3,
  //     img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will creating unique ai generated artworks mid journey ai artist",
  //     price: 1199,
  //     star: 5,
  //     username: "Carol Steve",
  //     title: "Digital Billboards",
  //   },
  //   {
  //     id: 4,
  //     img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create custom ai generated artwork using your photos",
  //     price: 9999,
  //     star: 4,
  //     username: "Don Weber",
  //     title: "Billboards",
  //   },
  //   {
  //     id: 5,
  //     img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will recreate your dreams in high quality pictures",
  //     price: 5999,
  //     star: 5,
  //     username: "Audrey Richards",
  //     title: "Street Furniture",
  //   },
  //   {
  //     id: 6,
  //     img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create ai digital art illustration hyper realistic painting",
  //     price: 7999,
  //     star: 4,
  //     username: "Walton Shepard ",
  //     title: "Wallscapes",
  //   },
  //   {
  //     id: 7,
  //     img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will generate images with your prompts using ai dalle",
  //     price: 8999,
  //     star: 5,
  //     username: "Waverly Schaefer",
  //     title: "Poster",
  //   },
  //   {
  //     id: 8,
  //     img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     desc: "I will create custom art using midjourney generator",
  //     price: 1100,
  //     star: 4,
  //     username: "Wilton Hunt",
  //     title: "Digital Billboards",
  //   },
  // ];
  export const gigsdetails = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Promote Your Brand on Prime Billboard Locations",
      price: 82678,
      star: 5,
      username: "Anna Bell",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc:
        "Captivating Wallscapes that Transform Urban Spaces into Eye-Catching Brand Experiences.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 20 X 10 ft.",
        "Location: Nikol, Ahmedabad",
        "Target Audience: Youth, Fashion Enthusiasts",
        "Additional Design Elements:  Custom Branding,  Animations"
      ],
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ultra high quality character art with ai",
      price: 7999,
      star: 5,
      username: "Lannie Coleman",
      title: "Poster",
      shortTitle: "Posters",
      shortDesc: "Eye-Catching Posters to Promote Your Brand in Various Settings.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 10 X 15 ft.",
        "Location: Maninagar, Ahmedabad",
        "Target Audience:  Families,  Foodies",
        "Additional Design Elements:  Special Effects"
      ],
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will creating unique ai generated artworks mid journey ai artist",
      price: 1199,
      star: 5,
      username: "Carol Steve",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Engaging Digital Billboard Campaigns to Capture Attention.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 15 X 25 ft.",
        "Location: Ellisbridge, Ahmedabad",
        "Target Audience:  Students, Young Professionals",
        "Additional Design Elements:  Interactive Features,  Animation",
      ],
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 9999,
      star: 4,
      username: "Don Weber",
      title: "Billboards",
      shortTitle: "Billboards",
      shortDesc: "Striking Billboard Visuals to Boost Brand Awareness.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 12 X 18 ft.",
        "Location: Navrangpura, Ahmedabad",
        "Target Audience:  Families,  Shoppers",
        "Additional Design Elements:  Custom Branding,  Call to Action"
      ],
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will recreate your dreams in high quality pictures",
      price: 5999,
      star: 5,
      username: "Audrey Richards",
      title: "Street Furniture",
      shortTitle: "Street Furniture",
      shortDesc:
        "Street Furniture Ads that Blend Seamlessly with the Urban Landscape.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 5 X 8 ft.",
        "Location: Ashram Road, Ahmedabad",
        "Target Audience:  Commuters,  Pedestrians",
        "Additional Design Elements:  Creative Typography,  Minimalist Style"
      ],
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc:
        "Create captivating wallscapes that transform urban spaces into eye-catching brand experiences.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 15 X 20 ft.",
        "Location:  Vastrapur, Ahmedabad",
        "Target Audience:  Tech Enthusiasts,  Young Adults",
        "Additional Design Elements:  Interactive Elements,  Lighting Effects"
      ],
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate images with your prompts using ai dalle",
      price: 8999,
      star: 5,
      username: "Waverly Schaefer",
      title: "Poster",
      shortTitle: "Posters",
      shortDesc: "Craft eye-catching posters that grab attention and promote your brand in various settings.",
      deliveryDate: 3,
      revisionNumber: 2,
      features: [
        "Size: 10 X 15 ft.",
        "Location:  Satellite, Ahmedabad",
        "Target Audience:  Families,  Families with Children",
        "Additional Design Elements:  Bright Colors,  Fun Illustrations"
      ],
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom art using midjourney generator",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Create engaging, eye-catching digital billboard campaigns that capture attention and drive results.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Minimalist Design,  Brand-Specific Imagery"
      ],
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc:
        "Create captivating wallscapes that transform urban spaces into eye-catching brand experiences.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 15 X 25 ft.",
        "Location:  Bodakdev, Ahmedabad",
        "Target Audience:  Students,  Young Professionals",
        "Additional Design Elements:  Bold Typography,  Creative Layout"
      ],
    },
    {
      id: 10,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Create engaging, eye-catching digital billboard campaigns that capture attention and drive results.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 10 X 12 ft.",
        "Location:  C.G. Road, Ahmedabad",
        "Target Audience:  Shoppers,  Fashion Enthusiasts",
        "Additional Design Elements:  Animation,  Special Effects"
      ],
    },
    {
      id: 11,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc:
        "Create captivating wallscapes that transform urban spaces into eye-catching brand experiences.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 20 X 15 ft.",
        "Location:  Drive-In Road, Ahmedabad",
        "Target Audience:  Families,  Young Adults",
        "Additional Design Elements:  Custom Typography,  Brand-Specific Imagery"
      ],
    },
    {
      id: 12,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Create engaging, eye-catching digital billboard campaigns that capture attention and drive results.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 18 X 12 ft.",
        "Location:  S.G. Highway, Ahmedabad",
        "Target Audience:  Business Professionals,  Executives",
        "Additional Design Elements:  Bold Colors,  Call to Action"
      ],
    },
    {
      id: 13,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc:
        "Create captivating wallscapes that transform urban spaces into eye-catching brand experiences.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 20 X 15 ft.",
        "Location:  Ashram Road, Ahmedabad",
        "Target Audience:  Students,  Young Professionals",
        "Additional Design Elements:  Interactive Elements,  Lighting Effects"
      ],
    },
    {
      id: 14,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 1100,
      star: 4,
      username: "Wilton Hunt",
      title: "Digital Billboards",
      shortTitle: "Digital Billboards",
      shortDesc: "Create engaging, eye-catching digital billboard campaigns that capture attention and drive results.",
      deliveryDate: 4,
      revisionNumber: 2,
      features: [
        "Size: 15 X 10 ft.",
        "Location:  Ellisbridge, Ahmedabad",
        "Target Audience:  Families,  Foodies",
        "Additional Design Elements:  Animation,  Special Effects"
      ],
    },
    {
      id: 15,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 7999,
      star: 4,
      username: "Walton Shepard ",
      title: "Wallscapes",
      shortTitle: "Wallscapes",
      shortDesc:
        "Create captivating wallscapes that transform urban spaces into eye-catching brand experiences.",
      deliveryDate: 2,
      revisionNumber: 3,
      features: [
        "Size: 12 X 18 ft.",
        "Location:  Navrangpura, Ahmedabad",
        "Target Audience:  Families,  Shoppers",
        "Additional Design Elements:  Creative Typography,  Minimalist Style"
      ],
    }
  ]; 